modLoader="kotlinfml" #mandatory
loaderVersion="[24,)" #mandatory (24 is current forge version)
#issueTrackerURL="http://my.issue.tracker/" #optional
#displayURL="http://example.com/" #optional
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Superloup10" #optional
[[mods]] #mandatory
modId="wolflin" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Wolflin" #mandatory
#updateJSONURL="http://myurl.me/" #optional
description='''
This is a long form description of the mod. You can write whatever you want here

Have some lorem ipsum.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis lacinia magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sagittis luctus odio eu tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque volutpat ligula eget lacus auctor sagittis. In hac habitasse platea dictumst. Nunc gravida elit vitae sem vehicula efficitur. Donec mattis ipsum et arcu lobortis, eleifend sagittis sem rutrum. Cras pharetra quam eget posuere fermentum. Sed id tincidunt justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
'''

[[dependencies.wolflin]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[24,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.wolflin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13]"
    ordering="NONE"
    side="BOTH"